CREATE OR REPLACE VIEW ANALYTICS.BI_ORDER_PAYMENTS AS
SELECT
	OP.ORDER_ID,
	OP.PAYMENT_SEQUENTIAL,
	O.CUSTOMER_ID,
	O.ORDER_PURCHASE_TIMESTAMP AS ORDER_PURCHASE_DATE,
	OP.PAYMENT_TYPE,
	OP.PAYMENT_INSTALLMENTS,
	OP.PAYMENT_VALUE
FROM
	RAW.OLIST_ORDER_PAYMENTS_DATASET OP
	JOIN RAW.OLIST_ORDERS_DATASET O ON OP.ORDER_ID = O.ORDER_ID;