CREATE OR REPLACE VIEW ANALYTICS.BI_ORDER_ITEMS AS
SELECT
	OI.ORDER_ID,
	OI.ORDER_ITEM_ID,
	O.CUSTOMER_ID,
	O.ORDER_PURCHASE_TIMESTAMP AS ORDER_PURCHASE_DATE,
	O.ORDER_APPROVED_AT,
	O.ORDER_DELIVERED_CARRIER_DATE,
	O.ORDER_DELIVERED_CUSTOMER_DATE,
	O.ORDER_ESTIMATED_DELIVERY_DATE,
	OI.PRODUCT_ID,
	OI.SELLER_ID,
	OI.PRICE,
	OI.FREIGHT_VALUE,
	(OI.PRICE + OI.FREIGHT_VALUE) AS TOTAL_ITEM_VALUE
FROM
	RAW.OLIST_ORDER_ITEMS_DATASET OI
	JOIN RAW.OLIST_ORDERS_DATASET O ON OI.ORDER_ID = O.ORDER_ID