CREATE OR REPLACE VIEW ANALYTICS.BI_ORDERS AS
SELECT
	O.ORDER_ID,
	O.CUSTOMER_ID,
	O.ORDER_STATUS,
	O.ORDER_PURCHASE_TIMESTAMP AS ORDER_PURCHASE_DATE,
	O.ORDER_APPROVED_AT,
	O.ORDER_DELIVERED_CARRIER_DATE,
	O.ORDER_DELIVERED_CUSTOMER_DATE,
	O.ORDER_ESTIMATED_DELIVERY_DATE
FROM
	RAW.OLIST_ORDERS_DATASET O;